
export const GET_CITIES = "GET_CITIES";
export const SET_CITIES = "SET_CITIES";

export const SET_SELECTED_CITY="SET_SELECTED_CITY";
export const GET_SELECTED_CITY="GET_SELECTED_CITY";

export const GET_CITY_WEATHER = "GET_CITY_WEATHER";
export const SET_CITY_WEATHER = "SET_CITY_WEATHER";

export const GET_MULTIPLE_CITY_WEATHER = "GET_MULTIPLE_CITY_WEATHER";
export const SET_MULTIPLE_CITY_WEATHER = "SET_MULTIPLE_CITY_WEATHER";
export const TOGGLE_FAVORITE = "TOGGLE_FAVORITE";